# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compiledplayergamestats',
            name='pdo',
        ),
        migrations.AddField(
            model_name='compiledplayergamestats',
            name='ab',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compiledplayergamestats',
            name='offbsa',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compiledplayergamestats',
            name='offga',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compiledplayergamestats',
            name='offgf',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compiledplayergamestats',
            name='offmsa',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compiledplayergamestats',
            name='offsa',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compiledplayergamestats',
            name='timeOffIce',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compiledgoaliegamestats',
            name='period',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='compiledgoaliegamestats',
            name='strength',
            field=models.CharField(db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='compiledplayergamestats',
            name='period',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='compiledplayergamestats',
            name='strength',
            field=models.CharField(db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthCity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthCountry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthStateProvince',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='firstName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='fullName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='lastName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='primaryPositionCode',
            field=models.CharField(blank=True, choices=[(b'R', b'Right Wing'), (b'C', b'Center'), (b'L', b'Left Wing'), (b'D', b'Defenseman'), (b'G', b'Goalie')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='rosterStatus',
            field=models.CharField(blank=True, choices=[(b'Y', b'Yes'), (b'N', b'No'), (b'I', b'IR')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
