# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_playergamefilterstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamefilterstats',
            name='blockedShotsAgainst',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamefilterstats',
            name='blockedShotsFor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamefilterstats',
            name='defensiveZoneStarts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamefilterstats',
            name='highDangerScoringChancesAgainst',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamefilterstats',
            name='highDangerScoringChancesFor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamefilterstats',
            name='individualBlockedShots',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamefilterstats',
            name='individualHighDangerScoringChances',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamefilterstats',
            name='individualMissedShots',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamefilterstats',
            name='individualScoringChances',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamefilterstats',
            name='individualShots',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamefilterstats',
            name='individualShotsBlocked',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamefilterstats',
            name='missedShotsAgainst',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamefilterstats',
            name='missedShotsFor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamefilterstats',
            name='offensiveZoneStarts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamefilterstats',
            name='scoringChancesAgainst',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamefilterstats',
            name='scoringChancesFor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamefilterstats',
            name='shotsAgainst',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergamefilterstats',
            name='shotsFor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
