# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20161127_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamefilterstats',
            name='neutralZoneStarts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
