# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0002_auto_20160224_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayMedia',
            fields=[
                ('external_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mediatype', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('blurb', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='preview')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playbyplay.Game')),
                ('play', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playbyplay.PlayByPlay')),
            ],
            options={
                'verbose_name': 'Media Files',
            },
        ),
    ]
