# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0002_auto_20160224_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
                ('mediatype', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('blurb', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='preview')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playbyplay.PlayByPlay')),
            ],
        ),
    ]
