# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0003_playmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playmedia',
            name='play',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
