# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0004_auto_20161113_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='playmedia',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='playbyplay.Game'),
            preserve_default=False,
        ),
    ]
