# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbyplay', '0004_auto_20161116_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameType',
            field=models.CharField(choices=[(b'PR', b'Pre-Season'), (b'R', b'Regular Season'), (b'P', b'Playoffs'), (b'A', b'All-Star Game')], max_length=2),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='blocked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='evenTimeOnIce',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='faceOffWins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='faceoffTaken',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='giveaways',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='penaltyMinutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='period',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='plusMinus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='powerPlayAssists',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='powerPlayGoals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='powerPlayTimeOnIce',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='shortHandedAssists',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='shortHandedGoals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='shortHandedTimeOnIce',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='shots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='takeaways',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='timeOnIce',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
