# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('season', models.IntegerField()),
                ('goalsAgainst', models.IntegerField(blank=True, null=True)),
                ('goalsScored', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField()),
                ('gamesPlayed', models.IntegerField()),
                ('streakCode', models.CharField(blank=True, max_length=3, null=True)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('ot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('shortName', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('abbreviation', models.CharField(max_length=3)),
                ('teamName', models.CharField(max_length=50)),
                ('locationName', models.CharField(max_length=50)),
                ('firstYearOfPlay', models.IntegerField()),
                ('conference', models.CharField(choices=[(b'W', b'Western'), (b'E', b'Eastern')], max_length=1)),
                ('division', models.CharField(choices=[(b'M', b'Metropolitan'), (b'A', b'Atlantic'), (b'C', b'Central'), (b'P', b'Pacific')], max_length=1)),
                ('officialSiteUrl', models.URLField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('timeZone', models.CharField(blank=True, max_length=50, null=True)),
                ('timeZoneOffset', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='venue',
            unique_together=set([('name', 'city')]),
        ),
        migrations.AddField(
            model_name='team',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Venue'),
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='seasonstats',
            unique_together=set([('date', 'team')]),
        ),
    ]
