# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_teamgamestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamgamestats',
            name='corsiAgainst',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamgamestats',
            name='corsiFor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamgamestats',
            name='hitsAgainst',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamgamestats',
            name='hitsFor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
