# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20161125_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamgamestats',
            name='period',
            field=models.CharField(choices=[(b'all', b'All'), (b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'OT')], db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='teamgamestats',
            name='scoresituation',
            field=models.CharField(choices=[(b'all', b'All'), (b't3+', b'Trailing by 3+'), (b't2', b'Trailing by 2'), (b't1', b'Trailing by 1'), (b't', b'Tied'), (b'l1', b'Leading by 1'), (b'l2', b'Leading by 2'), (b'l3+', b'Leading by 3+'), (b'w1', b'Within 1')], db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='teamgamestats',
            name='teamstrength',
            field=models.CharField(choices=[(b'all', b'All'), (b'even', b'Even Strength 5v5'), (b'pp', b'Power Play'), (b'pk', b'Short Handed'), (b'4v4', b'4v4'), (b'og', b'Opposing Goalie Pulled'), (b'tg', b'Team Goalie Pulled'), (b'3v3', b'3v3')], db_index=True, max_length=6),
        ),
    ]
