# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('key', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
        ),
    ]
